name: Run Go Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 17 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # 使用したいGoのバージョンを指定します
    - name: Make dir
      run: mkdir out
    - name: Run Go program
      run: go run main.go > ./out/feed.xml # 実行したいGoのファイルを指定します

    - name: SFTP upload feed.xml
      uses: Dylan700/sftp-upload-action@latest # SFTPアップロード用のアクション
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }} # オプション、デフォルトは22

        uploads: |
          ./out/ => /blob-store/public/

